Modernize Gradle config and release script
(From declaration hints plugin)

diff --git a/release b/release
--- a/release
+++ b/release
@@ -9,6 +9,24 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
+confirm() {
+    read -p "${1:-Continue?} (Y/N): " confirm
+
+    case "$confirm" in
+    [yY][eE][sS]|[yY])
+        # Continue
+        ;;
+    [nN][oO]|[nN])
+        echo "Canceled."
+        exit 1
+        ;;
+    *)
+        echo "Invalid response. Aborting..."
+        exit 2
+        ;;
+    esac
+}
+
 version=$1; shift
 
 if [ -z "$version" ]; then
@@ -18,7 +36,7 @@ fi
 
 # TODO: Can't be dirty!
 
-git tag "v${version}"
+git tag "v${version}" || [ "$(git name-rev --name-only --tags HEAD)" = "v${version}" ]
 
 export ORG_GRADLE_PROJECT_pluginReleaseVersion="$version"
 
@@ -27,5 +45,13 @@ export ORG_GRADLE_PROJECT_pluginReleaseVersion="$version"
 
 cp -a build/distributions/php_aliases-intellij-plugin{,-v${version}}.zip
 
-./gradlew runIde
+./gradlew runIde || :
 
+confirm "Push commits and tag 'v${version}' to GitHub?"
+git push github
+git push github "v${version}"
+
+if confirm "Tag 'v${version}' as 'latest' and FORCE push to GitHub?"; then
+    git tag --force latest "v${version}"
+    git push --force github latest
+fi
